### ISSUE TITLE
Image Enhancement Techniques

### ISSUE THREAD

**Issue by masoudnick** [alitourani/Iranis-dataset#2]
Hi dear @alitourani 
I read your paper and a question came to me.
What is the best way to enhance license plate images? and what method did you use?
I would appreciate if you helped me with this.

**Comment by alitourani** [comment]
Dear @masoudnick 
Thanks for the interest.
Your question is a bit general. There are several state-of-the-art Image Enhancement techniques available.
In our case, we usually use a Histogram Equalization (HE) method to standardize the intensities of the input image by spreading out the most recurrent ones, which results in an improved contrast. It all depends on the quality of the input image.
You can apply other methods such as color correction, image defogging, white balance, fusion-based methods, etc. regarding your own case.
